      - name: Run Bot with Telegram (9:20 AM IST only)
        if: github.event.schedule == '50 3 * * 1-5'
        run: python daily_bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

      - name: Run Bot without Telegram (All other times)
        if: github.event.schedule != '50 3 * * 1-5'
        run: python daily_bot.py
